#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  7 00:39:35 2022

@author: Charles Thomas Wallace Truscott

Byron Bay NSW 2481

127 Broken Head Rd, Suffolk Park NSW 2481

Massachusetts Institute of Technology, Harvard via edX student

Fine for permutations of the first odd number, 3, and fine for permutations of the second even number, 4

Need to prove theorem for all permutation sizes of even, odd and prime numbers (quick arithmetic in head presumed a conjecture is that one less than each prime number is an even number). Guessing factors of a number are the indices..

One quick conjecture is that the inner loop is n!/n times executed once each has taken the place of the subscript up to `n` times and switched with the subscript 0

Thank you Massachusetts Institute of Technology, need to prove this for all even, odd and prime factorial input, perhaps recursively proving the base cases for 0, 1, 2, using the algorithm for 3 and 4, and splitting all factors of subsequent numbers into a combinatorial definition of blocks of 3 and for (e.g. for nine the permutation applied 3 times for 3 blocks of 3 in definition, for 11 the permutation algorithm applied in a single block of one for 5 permutation boxes of 2)

runfile('/home/alienware/Desktop/permutations_alg_complex.py', wdir='/home/alienware/Desktop')
['D', 'B', 'C', 'A']
['B', 'D', 'C', 'A']
['B', 'C', 'D', 'A']
['A', 'C', 'D', 'B']
['C', 'A', 'D', 'B']
['C', 'D', 'A', 'B']
['D', 'A', 'C', 'B']
['A', 'D', 'C', 'B']
['A', 'C', 'D', 'B']
['B', 'C', 'D', 'A']
['C', 'B', 'D', 'A']
['C', 'D', 'B', 'A']
['D', 'B', 'A', 'C']
['B', 'D', 'A', 'C']
['B', 'A', 'D', 'C']
['C', 'A', 'D', 'B']
['A', 'C', 'D', 'B']
['A', 'D', 'C', 'B']
['A', 'B', 'C', 'D']
['B', 'A', 'C', 'D']
['B', 'C', 'A', 'D']
['D', 'C', 'A', 'B']
['C', 'D', 'A', 'B']
['C', 'A', 'D', 'B']
24

runfile('/home/alienware/Desktop/permutations_alg_complex.py', wdir='/home/alienware/Desktop')
['C', 'B', 'A']
['B', 'C', 'A']
['C', 'A', 'B']
['A', 'C', 'B']
['A', 'B', 'C']
['B', 'A', 'C']
6
{truncated input}

...


1 is odd
1 is the modulo of the odd number
638 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
640 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
642 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
644 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
646 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
648 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
650 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
652 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
654 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
656 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
658 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
660 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
662 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
664 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
666 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
668 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
670 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
672 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
674 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
676 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
678 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
680 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
682 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
684 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
686 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
688 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
690 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
692 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
694 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
696 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
698 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
700 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
702 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
704 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
706 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
708 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
710 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
712 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
714 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
716 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
718 is even
4 is the modulo of the even number
5 is odd
5 is the modulo of the odd number
720 is even
0 is the modulo of the even number
Count is: 721
0 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
2 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
4 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
6 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
8 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
10 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
12 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
14 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
16 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
18 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
20 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
22 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
24 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
26 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
28 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
30 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
32 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
34 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
36 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
38 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
40 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
42 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
44 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
46 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
48 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
50 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
52 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
54 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
56 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
58 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
60 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
62 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
64 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
66 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
68 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
70 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
72 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
74 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
76 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
78 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
80 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
82 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
84 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
86 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
88 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
90 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
92 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
94 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
96 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
98 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
100 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
102 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
104 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
106 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
108 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
110 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
112 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
114 is even
4 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
116 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
118 is even
3 is the modulo of the even number
4 is odd
4 is the modulo of the odd number
120 is even
0 is the modulo of the even number
Count is: 842
0 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
2 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
4 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
6 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
8 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
10 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
12 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
14 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
16 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
18 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
20 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
22 is even
2 is the modulo of the even number
3 is odd
3 is the modulo of the odd number
24 is even
0 is the modulo of the even number
Count is: 867
0 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
2 is even
2 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
4 is even
1 is the modulo of the even number
2 is odd
2 is the modulo of the odd number
6 is even
0 is the modulo of the even number
Count is: 874
0 is even
0 is the modulo of the even number
1 is odd
1 is the modulo of the odd number
2 is even
0 is the modulo of the even number
Count is: 877
0 is even
0 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
Count is: 879
0 is even
0 is the modulo of the even number
0 is odd
0 is the modulo of the odd number
2 is even
0 is the modulo of the even number
Count is: 882
882

...


"""

def factorial(n):
    if n == 1:
        return 1
    if n == 2:
        return 2
    else:
        y = 2
        for x in range(3, n + 1):
            y *= x
        return int(y)
    
def permutation(R):
    f = factorial(len(R))
    f_l = len(R) - 1
    f_r = factorial(len(R) - 1)
    f_rc = factorial(len(R) - 1)
    count = 0
    for x in range(0, len(R), 1):
        L = R.copy()
        temp = L[x]
        oth = L[0]
        L[0] = temp
        L[x] = oth
#        print(L)
        factorial_more = factorial(f_l)
#        print(factorial_more)
        for y in range(0, factorial_more + 1, 1):
#            print(y)
            if f_l == 0:
                f_l = 1
            if y % 2 != 0 and y % 2 != 1:
                print(y, "is prime")
                print(y % f_l, "is the modulo of the prime number")
            if y % 2 == 0:
                print(y, "is even")
                print(y % f_l, "is the modulo of the even number")
            if y % 2 == 1:
                print(y % f_l, "is odd")
                print(y % f_l, "is the modulo of the odd number")
            count += 1
        f_l -= 1
#            if factorial_less > 0:
#                for z in range(0, len(R), 1):
#                    print(y)
#                    ss = y % 2
#                    if factorial_less > 0:
#                        l = L[z]
#                        r = L[ss]
#                        L[z] = r
#                        L[ss] = l
#                        print(L)
#                        count += 1
#                    else:
#                        break
#                   count += 1

#            print(z)
#        f_l -= 1
        print("Count is: {}".format(count))

        f_r = factorial(len(R) - 1)
    print(count)
    return 0

def main():
#    permutation(['A', 'B', 'C'])
    String = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    L = []
    R = []
    p = 0
    permutation(['A', 'B', 'C', 'D', 'E', 'F', 'G'])
#    for x in range(2, 9, 2):
#        print(String[0:x + 1])
#        for y in String[0:x + 1]:
#            L.append(y)
#        R.append(L)
#        L = []
#    for z in range(0, int(len(R)), 1):
#        permutation(R[z])
#    permutation(['A', 'B', 'C', 'D', 'E'])
#    permutation(['A', 'B', 'C', 'D', 'E', 'F'])
#    permutation(['A', 'B', 'C', 'D', 'E', 'F', 'G'])
#    f.close()
if __name__ == "__main__": main()